import React from 'react';
import type { Metadata } from 'next';

import AppProvider from '@/context/appContext';

import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Spotify Playlists',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <AppProvider>
            <html lang="en">
                <body className={inter.className}>{children}</body>
            </html>
        </AppProvider>
    );
}
